### PR TITLE
ArduinoECCX08 compatability

### PR DESCRIPTION
**Pull request by gannaramu**
solves #35

### CODE REVIEW

**Comment by gannaramu** [comment]
@PaulStoffregen ArduinoECCX08 library doesn't work with teensy4.0 due to buffer length issue. I would appreciate it if you can review this PR.

**Comment by gannaramu** [comment]
added the missing prototype ``` buint8_t requestFrom(uint8_t address, uint8_t quantity, bool sendStop) ``` coming from API requirements of [Arduino]( https://github.com/arduino/ArduinoCore-API/blob/173e8eadced2ad32eeb93bcbd5c49f8d6a055ea6/api/HardwareI2C.h#L39)
closes #34 

This pull request would make teensy compatible with ArduinoECCX08 library

**Comment by PaulStoffregen** [comment]
Do these fully solve the problem?

https://github.com/PaulStoffregen/Wire/commit/2499ec67c2128629ee33697804f8650180293597

https://github.com/PaulStoffregen/Wire/commit/bd4689969970b26140f8554710d7daa24aa71070

**Comment by PaulStoffregen** [comment]
Duplicated on forum:
https://forum.pjrc.com/threads/68679-Wire-Library-missing-size_t-requestFrom(uint8_t-address-size_t-len-bool-stopBit)?highlight=ArduinoECCX08

**Comment by gannaramu** [comment]
Thank you @PaulStoffregen both those changes do solve the problem!

**Pull request closed without merging**
